function JhKA = JhKA_D(v,m17,h17,s17,m18,h18,n,nKA,hKA,V12,I,gNa17,gNa18,gK,gKA,g)
%JHKA_D
%    JHKA = JHKA_D(V,M17,H17,S17,M18,H18,N,NKA,HKA,V12,I,GNA17,GNA18,GK,GKA,G)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Jul-2019 18:34:57

t2 = v.*3.260869565221947e1;
t3 = t2+1.084782608694513e1;
t4 = exp(t3);
JhKA = [t4.*1.0./(t4+1.0).^2.*-1.95652173913084e2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-6.0];
