function JN = JN_D(v,m17,h17,s17,m18,h18,n,nKA,hKA,V12,I,gNa17,gNa18,gK,gKA,g)
%JN_D
%    JN = JN_D(V,M17,H17,S17,M18,H18,N,NKA,HKA,V12,I,GNA17,GNA18,GK,GKA,G)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Jul-2019 18:34:57

t2 = v.*-8.161044613720151;
t3 = t2-7.954298150161776e-1;
t4 = exp(t3);
t5 = v.*-6.0e1;
t6 = t5-2.2e1;
t7 = exp(t6);
t8 = t4+1.0;
t9 = t7.*1.25e-1;
t10 = t9+1.265000000000782e-2;
t11 = 1.0./t10;
t12 = t11+1.0;
t13 = 1.0./t12;
JN = [t4.*1.0./t8.^2.*t13.*2.448313384111971e2+t7.*1.0./t10.^2.*1.0./t12.^2.*(n.*3.0e1-3.0e1./t8).*7.5,0.0,0.0,0.0,0.0,0.0,t13.*-3.0e1,0.0,0.0];
