name: Publish previously executed runs of simulations to BioSimulations

on:
  workflow_dispatch:
    inputs:
      projectIds:
        description: 'Space-separate list of ids of projects to publish (e.g., "xxx" or "xxx yyy")'
        required: false
        default: ''
      ignoreErrors:
        description: 'Whether to publish runs even if some did not succeed: "0" (default) or "1"'
        required: false
        default: '0'

jobs:
  verify:
    name: Publish previously executed runs of simulations to BioSimulations
    runs-on: ubuntu-latest
    env:
      BIOSIMULATIONS_API_CLIENT_ID: ${{ secrets.BIOSIMULATIONS_API_CLIENT_ID }}
      BIOSIMULATIONS_API_CLIENT_SECRET: ${{ secrets.BIOSIMULATIONS_API_CLIENT_SECRET }}
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: dev
          lfs: true

      # Install requirements
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Setup pip cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/Python
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.optional.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip and setuptools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools

      # install package
      - name: Install the package
        run: python -m pip install -e .

      # Publish previously executed runs of simulations to BioSimulations
      - name: Publish previously executed runs of simulations to BioSimulations
        run: |
          args=""

          if [ ! -z "${{ github.event.inputs.projectIds }}" ]; then
            args="$args --project ${{ github.event.inputs.projectIds }}"
          fi

          if [ "${{ github.event.inputs.ignoreErrors }}" = "1" ]; then
            args="$args --ignore-errors"
          fi

          biosimulations-modeldb publish-runs $args
