name: Publish to BioSimulations

on:
  schedule:
    - cron: '0 1 * * 0' # weekly at 1:00 am on Sundays

  workflow_dispatch:
    inputs:
      updateCombineArchives:
        description: 'Whether to overwrite existing COMBINE/OMEX archives: "0" (default) or "1"'
        required: false
        default: '0'
      updateSimulationRuns:
        description: 'Whether to overwrite existing simulation runs: "0" (default) or "1"'
        required: false
        default: '0'

jobs:
  publish:
    name: Publish to BioSimulations
    runs-on: ubuntu-latest
    env:
      ENTREZ_EMAIL: ${{ secrets.ENTREZ_EMAIL }}

      BIOSIMULATIONS_API_CLIENT_ID: ${{ secrets.BIOSIMULATIONS_API_CLIENT_ID }}
      BIOSIMULATIONS_API_CLIENT_SECRET: ${{ secrets.BIOSIMULATIONS_API_CLIENT_SECRET }}

      BUCKET_ENDPOINT: https://localhost:4443
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      BUCKET_ACCESS_KEY_ID: ${{ secrets.BUCKET_ACCESS_KEY_ID }}
      BUCKET_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_ACCESS_KEY }}
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: dev

      # Install requirements
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Setup pip cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/Python
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.optional.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip and setuptools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools

      - name: Install XPP
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends wget make gcc libx11-dev libc6-dev

          cd /tmp
          wget http://www.math.pitt.edu/~bard/bardware/xppaut_latest.tar.gz
          mkdir xpp
          tar zxvf xppaut_latest.tar.gz --directory xpp
          cd xpp
          make
          sudo make install

          cd /tmp
          rm xppaut_latest.tar.gz
          rm -r xpp

      # install package
      - name: Install the package
        run: python -m pip install .

      # Publish models to BioSimulations
      - name: Publish models to BioSimulations
        run: |
          if [ "${{ github.event.inputs.updateCombineArchives }}" = "1" ]; then
            args="--update-combine-archives --update-simulation-runs"
          else
            if [ "${{ github.event.inputs.updateSimulationRuns }}" = "1" ]; then
              args="--update-simulation-runs"
            else
              args=""
            fi
          fi

          biosimulations-modeldb publish $args

      # Push compiled projects
      - id: commit-projects
        name: Commit the compiled projects
        run: |
          git config --local user.email "biosimulations.daemon@gmail.com"
          git config --local user.name "biosimulationsdaemon"
          git config pull.rebase false
          git stash
          git pull
          set +e
          git stash pop
          git add biosimulations_modeldb/source
          git lfs track biosimulations_modeldb/source/thumbnails/**/*.tar.gz
          git add -f biosimulations_modeldb/source/thumbnails/**/*.tar.gz
          git add -f biosimulations_modeldb/source/thumbnails/**/**/*.jpg
          git add -f biosimulations_modeldb/source/thumbnails/**/**/*.nxml
          git add biosimulations_modeldb/final
          git commit -m "Updated compiled projects [skip ci]"
          if [[ $? = 0 ]]; then
            changed=1
          else
            changed=0
          fi
          echo "::set-output name=changed::$changed"

      - name: Push the compiled projects
        if: steps.commit-projects.outputs.changed == '1'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
